TITLE = "Evolution"
SIZE = WIDTH, HEIGHT = ((1300, 900))
TEXT_WIDTH = 300
GAME_WIDTH = WIDTH - TEXT_WIDTH
FPS = 60
FRICTION = -0.05
TEXT_COLOR = (13,134, 141)
TEXT_COLOR_RED = (255,0, 0)
TEXT_SIZE = 20
MAX_ACTIVE_ROCKETS = 5
SHOW_POSITIONS = False
SPEED_HEALTH_DEPENDENCY = False

BUTTON_X = 0
BUTTON_A = 1
BUTTON_B = 2
BUTTON_Y = 3
BUTTON_L = 4
BUTTON_R = 5
BUTTON_SELECT = 8
BUTTON_START = 9
